### PR TITLE
Feat: likes and comments

### PR DESCRIPTION
**Pull request by SinchanaMS**
This request adds the following features: 

1. Like/Dislike Posts
2. Add/Delete Comment
3. Display the corresponding avatar in each post

### Preview:

1. Likes and Comments:

image

2. Display Corresponding Avatar:

image

### CODE REVIEW

**Review by Adarsh-Patel-Dev — APPROVED** [review]
Suggestion: You can put all icons/images in a separate folder & then use it
No further changes are required in code.
You can merge it to the dev branch

**Review by pankaj-prog — APPROVED** [review]
Suggestion: just a nit:  the handlers that you have defined inside the components, you can useCallback hook to memoize them.

**Comment by SinchanaMS** [comment]
> Suggestion: just a nit: the handlers that you have defined inside the components, you can useCallback hook to memoize them.

Thank you! I'll look into it once I'm done with all the features.

**Comment by SinchanaMS** [comment]
Thank you for the reviews. Merging to dev.

**Pull request merged**
